### ISSUE TITLE
pbkdf hashes

### ISSUE THREAD

**Issue by molangning** [spaze/hashes#29]
I was trying to add these hashes to seclists when I ran into a issue verifying the pbkdf hashes. The problem is that I can’t seem to get a magic hashes out of any entries for `pbkdf2-*` files. If anyone knows how to correctly hash the entries using cyberchef or php please leave the code here.

**Comment by spaze** [comment]
The PBKDF2 hashes are not really magic hashes that begin with `0e`. Similar to the plaintext passwords, they're "magic" in a different way due to pre-hashing, for example for SHA-256:
```php
$p1 = '2905814737452000000000000000000000000000000000000000000000000000000000000000000000_HASHCAT_FTW';
$p2 = '-7no| (rSnm95FNUX:R(ly*?,rpEu31D';
$h1 = hash_pbkdf2('sha256', $p1, 'foo', 123);
$h2 = hash_pbkdf2('sha256', $p2, 'foo', 123);
var_dump($h1 === $h2); // true
```
https://3v4l.org/aQAMs

**Comment by molangning** [comment]
It seems that I skipped the section in readme haha, thanks a lot!

**Comment by spaze** [comment]
No problem, cheers :-)

**Comment by molangning** [comment]
I added the hashes here, do you think there is any other parts that need work?
https://github.com/molangning/SecLists/tree/patch-php-magic-hash/Passwords/php-hashes

**Comment by spaze** [comment]
Sent you a PR https://github.com/molangning/SecLists/pull/12 with some small changes. I like to use the word "collisions" in quotes, because these are not real cryptographic collisions and when used without the quotes, some people will point out the fact, and they will be right :-)
